# Generated by Django 2.2.15 on 2020-08-16 11:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Name of Supplier', max_length=45, verbose_name='name')),
                ('lead_time', models.DurationField(default=datetime.timedelta(3), help_text='Lead Time of Supplier', verbose_name='lead_time')),
                ('payment_terms', models.PositiveSmallIntegerField(choices=[(0, 'Check'), (1, 'Cash')], default=0, help_text='Terms of Payment for the Supplier', verbose_name='payment_terms')),
            ],
            options={
                'verbose_name': 'Supplier',
                'verbose_name_plural': 'Suppliers',
                'ordering': ['name'],
            },
        ),
    ]
