# Generated by Django 2.2.15 on 2020-08-30 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Name of Brand', max_length=45, verbose_name='name')),
                ('description', models.TextField(blank=True, help_text='Description of Brand', verbose_name='description')),
                ('removed', models.BooleanField(default=False, help_text='Brand is removed', verbose_name='removed')),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brands',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Name of Category', max_length=45, verbose_name='name')),
                ('description', models.TextField(blank=True, help_text='Description of Category', verbose_name='description')),
                ('removed', models.BooleanField(default=False, help_text='Category is removed', verbose_name='removed')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='supplier',
            name='removed',
            field=models.BooleanField(default=False, help_text='Supplier is removed', verbose_name='removed'),
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Name of Item', max_length=45, verbose_name='name')),
                ('volume', models.CharField(blank=True, help_text='Volume of Item', max_length=45, verbose_name='volume')),
                ('code', models.CharField(blank=True, help_text='Code of Item', max_length=10, verbose_name='code')),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, help_text='Unit Cost of Item', max_digits=7, verbose_name='unit cost')),
                ('box_cost', models.DecimalField(decimal_places=2, default=0, help_text='Box Cost of Item', max_digits=7, verbose_name='box cost')),
                ('safety_stock', models.IntegerField(default=0, help_text='Box Cost of Item', verbose_name='box cost')),
                ('active', models.BooleanField(default=True, help_text='Is item active', verbose_name='active')),
                ('removed', models.BooleanField(default=False, help_text='Item is removed', verbose_name='removed')),
                ('quantity', models.IntegerField(default=0, help_text='Quantity of item', verbose_name='quantity')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='store.Brand', verbose_name='brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='store.Category', verbose_name='category')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='store.Supplier', verbose_name='supplier')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
                'ordering': ['name'],
            },
        ),
    ]
