version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: delibeary_db
      POSTGRES_USER: delibeary_user
      POSTGRES_PASSWORD: password
  web:
    build: .
    environment:
      - PYTHONDONTWRITEBYTECODE=1
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db